### PR TITLE
Add '-o' option to include only specific model numbers in airupnp

### PR DESCRIPTION
**Pull request by pwt**
This is a PR to address https://github.com/philippe44/AirConnect/issues/204.

The code has been compiled, but **not** tested -- as I struggle to maintain a functional build environment for AirConnect. Apologies for this; I'm happy to test any builds that get created.

### CODE REVIEW

**Comment by philippe44** [comment]
Do you think you could squash all the commits together?

**Comment by pwt** [comment]
Usually, I think the committer chooses ‘squash and merge’ when merging the PR, making it a single commit on the target branch: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/ 
If this doesn’t work for you for some reason, I’m happy to cancel the PR and create a new one.

**Comment by philippe44** [comment]
I can do that, it's just easier for me to view the patch as one item when possible. If you squash your commits on your fork, they will appear to me as one, I think (this is what I do usually)
- git rebase -i HEAD~N (N = number of commits to review)
- git push --force

**Comment by pwt** [comment]
> it's just easier for me to view the patch as one item when possible

But that's easy: you just click on 'files changed' above (https://github.com/philippe44/AirConnect/pull/205/files). That consolidates the changes. Then, you just squash merge.

**Comment by philippe44** [comment]
Now you know I'm a very casual user of GitHub :-)

**Comment by pwt** [comment]
Thanks @philippe44.

I'm no GitHub expert either, it's just that I've gone through the process of landing changes in another repo quite recently, so I had to comprehend the process :)

I'll do some testing of this option once you do your next builds. Assuming it passes, I'll close #204.

**Pull request merged**
