### PR TITLE
Make sure to start with flac header on each http connection

### PR DESCRIPTION
**Pull request by codepeon**

### CODE REVIEW

**Comment by philippe44** [comment]
I've upgraded to 8.0 and I still don't have the problem. But I took the time to review the code (the very initial core was not mine but I've changed it a lot and the flac addition was an early thing that I did not review after). I know that I'm stubborn :-) but because it's working 10% of the time in your case, I can't help thinking of a timing issue and there was a few things wrong wrt what was sent to the UPnP player that I corrected, and all could happen because of timing (some raw pcm frames could be sent). I also need to be careful because this code is shared with another of my apps and changes like re-sending falc header at every HTTP connection can have other side effects. Would you mind testing 0.1.0.4?

**Comment by codepeon** [comment]
It is fix in 0.1.0.4. I also took the liberty to find out exactly with change made it work. and it was
+// no real need for mutex here
+if (!ctx->playing) return NULL;

Thanks for fixing it.

**Comment by philippe44** [comment]
Cool - Thanks very much for your help. It's super useful to have other pair of eyes on code, especially I'm not a very good coder, so help is highly appreciated

**Comment by codepeon** [comment]
No worries! I really like this project.

I was to quick calling victory :(
I noticed a strange thing.
With your binary i get sound 10/10, but with the binary I compiled(without patches) i only get sound 7/10 (so its better now) but not perfect. What build environment do you use?

I'll just go with your binaries for now.

**Comment by philippe44** [comment]
That's weird - On Windows it's Embarcadero, on Linux it's a Kubuntu 14.10 32-bits box with cross-compilation for x86, x64, armhh, armel, ppc, sparc. I've built "my own" gcc for that

**Comment by codepeon** [comment]
I'm running arch linux on x86_64.
Well lets keep this PR closed since the issue is probably some kind of timing or thread contention issue that becomes visible on my platform. I'll get back to you when i have figured it out.

**Pull request closed without merging**
