### PR TITLE
Update updater

### PR DESCRIPTION
**Pull request by Hofyyy**
- Added curl support
- Added detection of default installation after initial installation. In this case the script is not located in the install dir.
- Added --depth=1 in git clone. Does reduce the checkout size and increase installation speed.
- Restructured into functions to avoid error messaged fomr rm -r for not existing tmp folder during first run.
- Restructured into functions to be more save outside the installation directory.

### CODE REVIEW

**Comment by philippe44** [comment]
Thanks!

**Comment by solelo** [comment]
Can you tell me how to run the updater? I can't seem to get it to work

**Comment by MacsInSpace** [comment]
Hey can I get in touch to pkg this/roll it into mine as a postflight/postinstall script? 
I added the launchctl script to start and stop the service too. :) https://github.com/MacsInSpace/AirCastAirUpnpMacOS.pkg

**Comment by MacsInSpace** [comment]
Working on updating this script for MacOS _and_ linux by testing the OS and processor.
https://gist.github.com/MacsInSpace/38cb4d033d936934e433ab625c589bef

Are the download URLs going to be stable in the following format?

aircasturl="https://github.com/philippe44/AirConnect/raw/master/bin/aircast-${OS}-${Processor}"
airupnpurl="https://github.com/philippe44/AirConnect/raw/master/bin/airupnp-${OS}-${Processor}"

**Pull request merged**
