### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by codepeon**
Fix some resouces/memory issues
Fix so all streams starts with flac header

### CODE REVIEW

**Comment by codepeon** [comment]
Ok, I'll drop send_all patch.
I'm not sure i follow what you mean with "not to detach". Will you fix it or should i update my patch, if so please clarify what you mean.

**Comment by philippe44** [comment]
When I create this thread, I detach it. I should not do that 

	case UPNP_DISCOVERY_SEARCH_TIMEOUT:	{
			pthread_attr_t attr;

			if (!glMainRunning) break;

			pthread_attr_init(&attr);
			pthread_attr_setstacksize(&attr, PTHREAD_STACK_MIN + 32*1024);
			pthread_create(&glUpdateMRThread, &attr, &UpdateMRThread, NULL);
			**pthread_detach(glUpdateMRThread);**
			pthread_attr_destroy(&attr);
			break;
		}

**Comment by codepeon** [comment]
Won't that cause alot of unjoined threads (one per UPNP_DISCOVERY_SEARCH_TIMEOUT) where we only have a reference to one (the latest)?

**Comment by codepeon** [comment]
When you received TEARDOWN you join the search_thread. Then when we shutdown raop_delete will try to join it again, which it not legal (undefined).
see: http://man7.org/linux/man-pages/man3/pthread_join.3.html

**Comment by codepeon** [comment]
Hm, that's strange i my sonos devices needs the re-send flac header patch otherwise i only get a  sound one 1 of 10 times. with the patch it never fails.

**Comment by philippe44** [comment]
Crap, yes you're right, I must join every non detached thread - too early in the morning for me. Let me think of a solution because if I don't wait for the updatethread to be terminated, then the resource freeing after have race conditions with the updating thread that might re-create them

**Comment by philippe44** [comment]
> edit: To late for mee ;) did not full understand what you meant. yes i can remove the done bool if i also remove the active_remote.search in serach_remote. Is that ok?

My bad, you're right otherwise, same issue, the thread would not be joined and resources not freed

**Comment by codepeon** [comment]
Teardown: Hm, it think that my commit message is wrong. The issue is that `search_remote ` sets the `ctx->active_remote.search = false;` if this happens while we are streaming and we shutdown airupnp we

**Comment by codepeon** [comment]
sorry.

**Comment by codepeon** [comment]
Yes i can send logs -d all=sdebug?

**Comment by codepeon** [comment]
OK, so i'll keep the soultion with the done variable. it that ok?

**Comment by philippe44** [comment]
> OK, so i'll keep the soultion with the done variable. it that ok?
Yes

> Yes i can send logs -d all=sdebug?
JUst the default level is good enough to start, no need to do the full thing (it's super verbose!)

**Comment by codepeon** [comment]
logs: https://gist.github.com/codepeon/273639245e5ff8454d8c834456e75397

**Comment by codepeon** [comment]
I can solve the UpdateMRThread theads on linux using pthread_tryjoin_np.
If it returns error we just skip the update and let the thread finish and do the update next time around (15-30s?). Does pthread_tryjoin_np exists on windows (google does not tell me).

**Comment by philippe44** [comment]
I've done various updates based on your suggestions (thank you!) - I can't merge the pull request as it's a bit too complicated, but I've uploaded my changes. I still need to understand what's happening wit your Sonos. What model is this and what version of Sonos apps do your run?

**Comment by codepeon** [comment]
I have sub, playbar, play 3 and some play 1s.
App: 8.1

**Comment by codepeon** [comment]
Lets continue the flac header discussion here https://github.com/philippe44/AirConnect/pull/5

**Pull request closed without merging**
