### PR TITLE
Airupnp mipsel build

### PR DESCRIPTION
**Pull request by vince-cheung**

### CODE REVIEW

**Comment by philippe44** [comment]
Do you still need that ?

**Comment by vince-cheung** [comment]
You can delete this pr. I see that you already support the mips version, but I still need support for the mipsel version, so if you can provide it, I'd appreciate it!

**Comment by philippe44** [comment]
I have a couple of questions then 
- would you mind telling what os/platform this is?
- were you able to rebuild things easily with the new version where everything should be sunmodules and scripts

**Comment by vince-cheung** [comment]
I use it on ubnt edgerouter x,  (Datesheet)[https://dl.ui.com/datasheets/edgemax/EdgeRouter_X_DS.pdf]. 
System based on Debian 9 (stretch): 
Linux 4.14.54-UBNT #1 SMP Thu Jun 30 07:04:36 UTC 2022 mips GNU/Linux

I haven't tried to compile the new version yet, but will try it later, I've been busy lately 😔

**Pull request closed without merging**
